env = false
telemetry = false

[install]
exact = true
linker = "hoisted"
minimumReleaseAge = 432000 # 5 days
minimumReleaseAgeExcludes = [
    "@willbooster/babel-configs",
    "@willbooster/biome-config",
    "@willbooster/eslint-config-js",
    "@willbooster/eslint-config-js-react",
    "@willbooster/eslint-config-next",
    "@willbooster/eslint-config-ts",
    "@willbooster/eslint-config-ts-react",
    "@willbooster/prettier-config",
    "@willbooster/wb",
    "next",
    "@next/*",
    "react",
    "react-dom"
]
